import os
import json
import re
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import SystemMessage, HumanMessage
from agents.logger import emit_agent_log

class AIScoreAgent:
    def __init__(self):
        self.model_name = "claude-3-5-sonnet-20240620"

    def evaluate(self, content: str) -> dict:
        emit_agent_log("AIScoreAgent", "Scanning content for AI signatures (Burstiness & Perplexity)...")
        
        system_prompt = """You are a highly advanced AI content detection algorithm.
Your goal is to analyze the provided text and determine the probability (0 to 100) that it was generated by an AI model (like ChatGPT, Claude, etc.).
Analyze two key metrics:
1. **Perplexity**: Does the text use highly predictable vocabulary and transition phrases common to LLMs?
2. **Burstiness**: Is the sentence length highly uniform (AI) or does it vary wildly with short/long sentences (Human)?

Return ONLY valid JSON with this exact structure:
{
  "ai_probability_score": <int between 0 and 100>,
  "reasoning": "<short string explaining why it looks like AI or Human>"
}
"""
        
        # We cap the content length to avoid unnecessarily massive context windows for a simple classification
        content_snippet = content[:8000] if len(content) > 8000 else content

        user_msg = f"Text to analyze:\n\n{content_snippet}"

        try:
            chat = ChatAnthropic(
                model=self.model_name,
                anthropic_api_key=os.getenv("ANTHROPIC_API_KEY"),
                timeout=120.0,
                max_tokens=300
            )
            response = chat.invoke([
                SystemMessage(content=system_prompt),
                HumanMessage(content=user_msg)
            ])
            
            text = response.content.strip()
            
            m = re.search(r'\{.*\}', text, re.DOTALL)
            if m:
                result = json.loads(m.group())
                score = result.get("ai_probability_score", 100)
                reasoning = result.get("reasoning", "Analyzed successfully.")
                emit_agent_log("AIScoreAgent", f"Scan complete. AI Probability Score: {score}%")
                return {"ai_probability_score": score, "reasoning": reasoning}
            else:
                emit_agent_log("AIScoreAgent", "Failed to parse JSON score.")
                return {"ai_probability_score": 100, "reasoning": "Fallback score applied due to parsing error."}
                
        except Exception as e:
            emit_agent_log("AIScoreAgent", f"Error during AI Detection: {str(e)}")
            return {"ai_probability_score": 100, "reasoning": f"Detection failed: {str(e)}"}
